-- 1. Pastikan kolom nama dapat menampung teks panjang
ALTER TABLE tipe_surat ALTER COLUMN nama TYPE VARCHAR(255);

-- 2. Bersihkan tipe surat lama
DELETE FROM tipe_surat;

-- 3. Masukkan seluruh data tipe surat baru (215 data)
INSERT INTO tipe_surat (buku_kode, kode, nama) VALUES
  ('PR', '01.01', 'Rencana Strategis'),
  ('PR', '01.02', 'Trilateral Meeting'),
  ('PR', '01.03', 'Rencana Kerja'),
  ('PR', '01.04', 'Rencana Kerja dan Anggaran'),
  ('PR', '02.01', 'Unit Utama'),
  ('PR', '02.02', 'Kantor Wilayah'),
  ('PR', '3', 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP)'),
  ('PR', '04.01', 'Laporan Tetap'),
  ('PR', '04.02', 'Laporan Insidentil'),
  ('PR', '05.01', 'Dengan Dewan Perwakilan Rakyat (DPR)'),
  ('PR', '05.02', 'Tingkat Kementerian'),
  ('PR', '05.03', 'Tingkat Unit Utama (Rapat Kerja Teknis)'),
  ('PR', '05.04', 'Tingkat Kantor Wilayah'),
  ('PR', '05.05', 'Rapat Pimpinan dan Rapat Staf'),
  ('PR', '06.01', 'Sidang Kabinet Terbatas'),
  ('PR', '06.02', 'Sidang Kabinet Paripurna'),
  ('KU', '01.01', 'Pedoman, Petunjuk, dan Administrasi Pelaksanaan Anggaran'),
  ('KU', '01.02', 'Daftar Isian Pelaksanaan Anggaran (DIPA)'),
  ('KU', '01.03', 'Penerimaan Negara Bukan Pajak (PNBP)'),
  ('KU', '02.01', 'Pedoman dan Petunjuk Administrasi Keuangan'),
  ('KU', '02.02', 'Penatausahaan Hibah'),
  ('KU', '02.03', 'Pejabat Perbendaharaan Negara'),
  ('KU', '02.04', 'Penyelesaian Kerugian Negara'),
  ('KU', '02.05', 'Penatausahaan Rekening Pemerintah'),
  ('KU', '03.01', 'Dokumen Pertanggungjawaban Belanja'),
  ('KU', '03.02', 'Buku Kas Umum dan Buku Pembantu'),
  ('KU', '03.03', 'Laporan Pertanggungjawaban (LPJ) Bendahara Pengeluaran'),
  ('KU', '03.04', 'LPJ Bendahara Penerimaan'),
  ('KU', '03.05', 'Penerimaan Negara Pajak'),
  ('KU', '04.01', 'Laporan Keuangan'),
  ('KU', '04.02', 'Rekonsiliasi dan Data Laporan Keuangan'),
  ('KU', '04.03', 'Penyelesaian Tindak Lanjut Temuan Hasil Pemeriksaan BPK dan Inspektorat Jenderal'),
  ('OT', '01.01', 'Organisasi dan Tata Kerja Kementerian'),
  ('OT', '01.02', 'Organisasi dan Tata Kerja Kantor Wilayah'),
  ('OT', '01.03', 'Organisasi dan Tata Kerja Unit Pelaksana Teknis (UPT)'),
  ('OT', '01.04', 'Evaluasi Kelembagaan'),
  ('OT', '02.01', 'Standarisasi Sarana Kerja'),
  ('OT', '02.02', 'Sistem, Prosedur dan Metode Kerja'),
  ('OT', '02.03', 'Analisa dan Uraian Jabatan'),
  ('OT', '03.01', 'Penilaian Mandiri Pelaksanaan Reformasi Birokrasi (PMPRB)'),
  ('OT', '03.02', 'Zona Integritas (ZI)'),
  ('OT', '03.03', 'Evaluasi Reformasi Birokrasi'),
  ('OT', '4', 'Instruksi Menteri'),
  ('SA', '01.01', 'Inventarisasi Jabatan/Peta Jabatan'),
  ('SA', '01.02', 'Evaluasi Jabatan'),
  ('SA', '01.03', 'Usulan Formasi'),
  ('SA', '01.04', 'Alokasi Formasi'),
  ('SA', '02.01', 'Proses Penerimaan SDM Aparatur'),
  ('SA', '02.02', 'Berkas Lamaran Yang Tidak Diterima'),
  ('SA', '02.03', 'Surat Keputusan Calon Pegawai Negeri Sipil (CPNS)/Pegawai Negeri Sipil (PNS) Kolektif'),
  ('SA', '02.04', 'Penerimaan SDM Aparatur dari Politeknik Ilmu Pemasyarakatan dan Politeknik Imigrasi'),
  ('SA', '02.05', 'Ujian Dinas dan Ujian Penyesuaian Ijazah'),
  ('SA', '03.01', 'Pengangkatan CPNS'),
  ('SA', '03.02', 'Pengangkatan PNS'),
  ('SA', '03.03', 'Pengangkatan Jabatan Struktural'),
  ('SA', '03.04', 'Pengangkatan Jabatan Fungsional'),
  ('SA', '04.01', 'Alih Tugas/Diperbantukan/Dipekerjakan/Pelaksana'),
  ('SA', '04.02', 'Pelaksana Harian/Pelaksana Tugas'),
  ('SA', '04.03', 'Pencantuman Gelar Akademik'),
  ('SA', '04.04', 'Kenaikan Gaji Berkala (KGB)'),
  ('SA', '04.05', 'Kenaikan Pangkat (KP)/Golongan'),
  ('SA', '04.06', 'Peninjauan Masa Kerja'),
  ('SA', '04.07', 'Berkas Badan Pertimbangan Jabatan dan Kepangkatan (Baperjakat)'),
  ('SA', '04.08', 'Pengaktifan Kembali dari Cuti Luar Tanggungan Negara (CTLN) dan Hukuman Disiplin'),
  ('SA', '05.01', 'Penilaian Prestasi Kerja Pegawai (PPKP)'),
  ('SA', '05.02', 'Pembinaan Disiplin dan Kode Etik'),
  ('SA', '05.03', 'Pemberian Penghargaan dan Tanda Jasa'),
  ('SA', '06.01', 'Pengembangan Kompetensi Jabatan Pimpinan Tinggi dan Administrasi'),
  ('SA', '06.02', 'Pengembangan Kompetensi Fungsional'),
  ('SA', '06.03', 'Pengiriman Peserta Diklat'),
  ('SA', '06.04', 'Bea Siswa'),
  ('SA', '07.01', 'Tingkat Ringan (Pernyataan Tidak Puas, Teguran Lisan, Teguran Tertulis)'),
  ('SA', '07.02', 'Tingkat Sedang (Penundaan KGB, KP dan Penurunan Gaji)'),
  ('SA', '07.03', 'Tingkat Berat (Penurunan Pangkat, Pembebasan Jabatan, Pemberhentian Dengan Hormat/Tidak Dengan Hormat)'),
  ('SA', '08.01', 'Data SDM Aparatur'),
  ('SA', '08.02', 'Identitas Pegawai (Kartu Pegawai, Kartu Suami, Kartu Istri)'),
  ('SA', '08.03', 'Izin Kepegawaian (Izin Belajar, Tugas Belajar Dalam Negeri dan Luar Negeri)'),
  ('SA', '08.04', 'Keanggotaan SDM Aparatur Dalam Organisasi Sosial'),
  ('SA', '08.05', 'Daftar Hadir/Absensi SDM Aparatur'),
  ('SA', '09.01', 'Kesehatan'),
  ('SA', '09.02', 'Perumahan (Tabungan Perumahan (TAPERUM), Biaya Uang Muka)'),
  ('SA', '09.03', 'Tabungan dan Asuransi Pegawai Negeri (TASPEN)'),
  ('SA', '09.04', 'Cuti'),
  ('PB', '01.01', 'Usulan Rencana Kebutuhan BMN'),
  ('PB', '01.02', 'Rencana Kebutuhan BMN Kementerian'),
  ('PB', '01.03', 'Hasil Analisis Kebutuhan BMN'),
  ('PB', '01.04', 'Rencana Kebutuhan Aset Berwujud'),
  ('PB', '01.05', 'Rencana Kebutuhan Aset Tak Berwujud'),
  ('PB', '02.01', 'Pengelolaan Pengadaan Barang/Jasa'),
  ('PB', '02.02', 'Pengelolaan Layanan Pengadaan Secara Elektronik dan Data Informasi Pengadaan Barang/Jasa'),
  ('PB', '02.03', 'Pembinaan, Bimbingan, Pendampingan, dan Konsultasi Teknis Pengadaan Barang/Jasa'),
  ('PB', '02.04', 'Tindak Lanjut Hasil Pemeriksaan'),
  ('PB', '02.05', 'Laporan Pengadaan Barang/Jasa'),
  ('PB', '02.06', 'Telaahan Permasalahan Pengadaan Barang/Jasa'),
  ('PB', '02.07', 'Unit Kerja Pengadaan Barang dan Jasa (UKPBJ)'),
  ('PB', '02.08', 'Pendistribusian Barang Milik Negara'),
  ('PB', '03.01', 'Penggunaan Barang Milik Negara (BMN)'),
  ('PB', '03.02', 'Pemanfaatan Barang Milik Negara'),
  ('PB', '03.03', 'Pengamanan dan Pemeliharaan'),
  ('PB', '03.04', 'Rumah Negara'),
  ('PB', '04.01', 'Pencatatan Barang Milik Negara'),
  ('PB', '04.02', 'Inventarisasi'),
  ('PB', '04.03', 'Opname Fisik'),
  ('PB', '04.04', 'Rekonsiliasi Data Barang Milik Negara'),
  ('PB', '04.05', 'Pengawasan dan Pengendalian BMN'),
  ('PB', '04.06', 'Laporan Barang Milik Negara'),
  ('PB', '05.01', 'Penjualan'),
  ('PB', '05.02', 'Tukar Menukar'),
  ('PB', '05.03', 'Hibah'),
  ('PB', '05.04', 'Pemusnahan'),
  ('PB', '05.05', 'Penghapusan'),
  ('UM', '01.01', 'Persuratan'),
  ('UM', '01.02', 'Ucapan Terima Kasih/Ucapan Selamat'),
  ('UM', '02.01', 'Pemindahan Arsip'),
  ('UM', '02.02', 'Pemusnahan Arsip'),
  ('UM', '02.03', 'Penyerahan'),
  ('UM', '02.04', 'Pembinaan Kearsipan'),
  ('UM', '02.05', 'Pengawasan Kearsipan'),
  ('UM', '02.06', 'Monitoring dan Evaluasi'),
  ('UM', '03.01', 'Penggunaan Ruang dan Peralatan Kantor'),
  ('UM', '03.02', 'Penggunaan dan Penghunian Rumah Negara'),
  ('UM', '03.03', 'Penggunaan dan Pemeliharaan Kendaraan Dinas'),
  ('UM', '03.04', 'Penggunaan dan Pemeliharaan Barang Elektronik serta Mesin'),
  ('UM', '03.05', 'Pemeliharaan Gedung dan Bangunan serta Area Kantor'),
  ('UM', '03.06', 'Pemeliharaan Alat Kesehatan'),
  ('UM', '03.07', 'Perjalanan Dinas (Dalam Negeri/Luar Negeri)'),
  ('UM', '03.08', 'Penghematan Energi dan Air'),
  ('UM', '04.01', 'Penyelenggaraan Upacara'),
  ('UM', '04.02', 'Pelayanan Tamu, Acara Kedinasan, Jamuan dan Ramah Tamah'),
  ('UM', '04.03', 'Daftar Nama Pejabat dan Alamat'),
  ('UM', '05.01', 'Pengamanan Personil (VVIP/VIP)'),
  ('UM', '05.02', 'Pengamanan Lingkungan, Fisik dan Instalasi'),
  ('UM', '05.03', 'Pengamanan Dokumen dan Informasi Rahasia'),
  ('UM', '05.04', 'Laporan Keamanan'),
  ('UM', '05.05', 'Laporan Kejadian'),
  ('UM', '05.06', 'Bantuan Pengamanan'),
  ('UM', '06.01', 'Layanan Keagamaan dan Sosial'),
  ('UM', '06.02', 'Layanan Kesehatan Jasmani'),
  ('UM', '06.03', 'Pelayanan Kesehatan'),
  ('UM', '07.01', 'Akuisisi'),
  ('UM', '07.02', 'Pengolahan Bahan Pustaka'),
  ('UM', '07.03', 'Pangkalan Data Koleksi'),
  ('UM', '07.04', 'Layanan Perpustakaan'),
  ('UM', '07.05', 'Preservasi Bahan Pustaka'),
  ('UM', '07.06', 'Pengembangan Perpustakaan'),
  ('UM', '07.07', 'Pendidikan dan Pelatihan Perpustakaan'),
  ('UM', '07.08', 'Tenaga Perpustakaan'),
  ('PW', '01.01', 'Kebijakan Pengawasan'),
  ('PW', '01.02', 'Perjanjian Kinerja'),
  ('PW', '01.03', 'Program Kerja Pengawasan Tahunan (PKPT)'),
  ('PW', '01.04', 'Program Kerja Administrasi Umum (PKAU)'),
  ('PW', '01.05', 'Rapat Koordinasi Pengawasan (RAKORWAS)'),
  ('PW', '01.06', 'Ikhtisar Hasil Pengawasan'),
  ('PW', '02.01', 'Audit Kinerja & Informasi, Reviu dan Evaluasi'),
  ('PW', '02.02', 'Audit Tujuan Tertentu/Khusus'),
  ('PW', '02.03', 'Pemantauan/Monitoring'),
  ('PW', '02.04', 'Pengawasan Lainnya, Pendampingan, Sosialisasi, Perjanjian Kerja Sama'),
  ('PW', '03.01', 'Laporan Hasil Audit Kinerja (LHA/LHP), Informasi Data Pendukung Pemeriksaan Dalam Negeri dan Luar Negeri'),
  ('PW', '03.02', 'Laporan Hasil Audit Tujuan Tertentu (Audit Khusus)'),
  ('PW', '03.03', 'Pemantauan/Monitoring BPK RI, BPKP RI, ORI, Inspektorat Jenderal'),
  ('PW', '03.04', 'Pengawasan Lainnya, Pendampingan, Sosialisasi, Perjanjian Kerja Sama'),
  ('PW', '03.05', 'Inspektorat Jenderal'),
  ('PW', '04.01', 'Laporan Tindak Lanjut Hasil Audit Kinerja'),
  ('PW', '04.02', 'Laporan Tindak Lanjut Hasil Audit Khusus'),
  ('PW', '04.03', 'Tindak Lanjut BPKP RI, BPK RI, ITJEN'),
  ('PW', '05.01', 'Reviu'),
  ('PW', '05.02', 'Tindak Lanjut Reviu'),
  ('PW', '06.01', 'Whistle Blowing System (WBS)'),
  ('PW', '06.02', 'Gratifikasi'),
  ('PW', '06.03', 'Pengaduan Tertulis (SMS Gateway, PO BOX 3489, Email ITJEN)'),
  ('PW', '06.05', 'Pengaduan Melalui Aplikasi LAPOR (Layanan Pengaduan Secara Online Rakyat)'),
  ('PW', '06.06', 'Pengaduan Ombudsman'),
  ('PW', '07.01', 'Tanggapan/Telaahan Hukuman Disiplin Yang Tidak Ditindaklanjuti'),
  ('PW', '07.02', 'Tanggapan/Telaahan Hukuman Disiplin Yang Ditindaklanjuti'),
  ('PW', '07.03', 'Daftar Nama Pegawai Kementerian Imigrasi dan Pemasyarakatan yang Dikenakan Sanksi Hukuman Disiplin/Kartu Cela'),
  ('PK', '01.01', 'Registrasi Tahanan dan Anak'),
  ('PK', '01.02', 'Registrasi Narapidana dan Anak Binaan'),
  ('PK', '01.03', 'Registrasi Klien Pemasyarakatan'),
  ('PK', '01.04', 'Registrasi Titipan'),
  ('PK', '01.05', 'Administrasi Pelayanan Tahanan di Luar Rutan'),
  ('PK', '01.06', 'Peminjaman/Bon Narapidana dan Anak Binaan'),
  ('PK', '02.01', 'Admisi Orientasi'),
  ('PK', '02.02', 'Asesmen dan Klasifikasi'),
  ('PK', '03.01', 'Mutasi Tahanan dan Anak'),
  ('PK', '03.02', 'Mutasi Narapidana dan Anak Binaan'),
  ('PK', '03.03', 'Mutasi Klien Pemasyarakatan'),
  ('PK', '04.01', 'Layanan Kepribadian'),
  ('PK', '04.02', 'Layanan Kemandirian'),
  ('PK', '04.03', 'Layanan Pelindungan Hukum Tahanan dan Anak'),
  ('PK', '04.04', 'Pengeluaran Tahanan dan Anak'),
  ('PK', '04.05', 'Tim Pertimbangan Pemasyarakatan Pelayanan Tahanan dan Anak'),
  ('PK', '05.01', 'Pembinaan Kepribadian'),
  ('PK', '05.02', 'Pembinaan Kemandirian'),
  ('PK', '05.03', 'Asimilasi dan Integrasi Narapidana dan Anak Binaan'),
  ('PK', '05.04', 'Pengeluaran Narapidana dan Anak Binaan'),
  ('PK', '05.05', 'Tim Pertimbangan Pemasyarakatan Pembinaan Narapidana dan Anak Binaan'),
  ('PK', '06.01', 'Penelitian Kemasyarakatan'),
  ('PK', '06.02', 'Pendampingan Klien Pemasyarakatan dan Upaya Keadilan Restoratif Pemasyarakatan'),
  ('PK', '06.03', 'Pembimbingan Klien Pemasyarakatan'),
  ('PK', '06.04', 'Pengawasan Klien Pemasyarakatan'),
  ('PK', '06.05', 'Tim Pertimbangan Pemasyarakatan Pembimbingan Klien Pemasyarakatan'),
  ('PK', '07.01', 'Perawatan Kesehatan Dasar'),
  ('PK', '07.02', 'Perawatan Kesehatan Lanjutan'),
  ('PK', '07.03', 'Perawatan Kesehatan Khusus'),
  ('PK', '07.04', 'Kebutuhan Dasar dan Kesehatan Lingkungan'),
  ('PK', '08.01', 'Intelijen Pemasyarakatan'),
  ('PK', '08.02', 'Pencegahan Gangguan Keamanan dan Pemeliharaan Keamanan'),
  ('PK', '08.03', 'Penindakan dan Pemulihan'),
  ('PK', '09.01', 'Pencegahan dan Pengendalian'),
  ('PK', '09.02', 'Fasilitasi Advokasi dan Investigasi Internal'),
  ('PK', '10.01', 'Pengelolaan Data dan Informasi'),
  ('PK', '10.02', 'Statistik Tahanan dan Anak'),
  ('PK', '10.03', 'Statistik Narapidana dan Anak Binaan'),
  ('PK', '10.04', 'Statistik Klien Pemasyarakatan'),
  ('PK', '10.05', 'Statistik Titipan')
ON CONFLICT (buku_kode, kode) DO UPDATE SET nama = EXCLUDED.nama;

-- 4. Verifikasi jumlah data
SELECT buku_kode, COUNT(*) as total FROM tipe_surat GROUP BY buku_kode ORDER BY buku_kode;
